version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: localpass42
      MYSQL_DATABASE: figures_db
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpass42
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: localpass42
    ports:
      - "8080:80"

volumes:
  mysql_data:
